### ISSUE TITLE
Cannot read `res.body` after calling async function. 

### ISSUE THREAD

**Issue by fbukevin** [davesag/mock-req-res#85]
With the following implementation, the function getRooms was called when running the test case. However, I cannot read the body of the response object after the function getRooms was called.
**Target Function**
```js
class RoomHandle {
    static async getRooms(req, res) {
        const hotelCode = req.session.hotel_code;
        const result = await Rooms.findByHotelCode(hotelCode.toString());
        res.send({ rooms: result.Items, count: result.Count, status: 'success' });
    }
}
```
**Test**
```js
const { expect } = require('chai');
const { mockRequest, mockResponse } = require('mock-req-res')
const RoomHandle = require('../controllers/RoomHandle');

describe('RoomHandle', () => {
    context('To', () => {
        const res = mockResponse();
        const req = mockRequest({ 
            session: {
                hotel_code: '234'
            }
        });
        
        before(async ()=>{
            await RoomHandle.getRooms(req, res);
        })

        console.log(res.body); // <=== undefined

        it('get room list with RoomHandle.getRooms', () => {        
            expect(res.body.status).to.equal('success')
            expect(res.body.rooms.Count).to.equal(1)
        });
    })

});
```

**Comment by davesag** [comment]
In your unit test you would need to use something like [`proxyquire`](https://github.com/thlorenz/proxyquire) to inject the  `Rooms` object, and replace it with a `stub` that `resolves` some sort of response.

The test you have written is more of an integration test than a unit test.  In a unit test you can't assume the existence of any external dependencies such as database models.  In an integration test you do need to run an active database and you don't use the mocked request and response objects.

It's important you note that the `request` and `response` objects you get from `mockRequest` and `mockResponse` are not real `request` and `response` objects and won't do anything you don't tell them to do, other than some very simple default behaviour.

Take a look at this [example of a server test](https://github.com/davesag/api-server-boilerplate/blob/develop/test/server/routes/v1/hello.test.js) vs the [unit test of the same controller](https://github.com/davesag/api-server-boilerplate/blob/develop/test/unit/api/v1/hello.test.js).
